### ISSUE TITLE
ARCHITECTURE -- MODEL SELECTION ==> next: flesh out model selection in report write-up.

### ISSUE THREAD

**Issue by Skenderbeu1405** [georgetown-analytics/Loan-Canoe#10]
KB:  Perhaps put in README file, show how we started and flowed our model selection. It would be helpful for everyone in class and also very best approach for us.

**Comment by Anne-Kl** [comment]
Created Initial Draft ReadMe and Summary Visual for final report and presentation; put in our Google Drive folder.  ReadMe is currently shown as Section IV (Overview) of the Draft Final Report.  Uploaded source PPT slide for Visual and copy/pasted placeholder image in our Google Slides.

**Comment by Skenderbeu1405** [comment]
Thanks Anne -- opening this back up so that the 'Project' automation puts it in the IN PROGRESS card: the last step is to flesh out the model selection in our write up -- as updated in the title.

**Comment by Anne-Kl** [comment]
Resolved in Phase 2 and 3 models
