### ISSUE TITLE
8/1 notes from meeting with Karen 

### ISSUE THREAD

**Issue by Skenderbeu1405** [georgetown-analytics/Loan-Canoe#15]
courtesy of Anne's notes.  Putting it into an issue here to make sure we address and complete each point. 

For notes on the 2nd week of August meeting with Karen, see other issue I (Blake/Skenderbeu1405) created and that is in-progress:
---

0. Cleaning up Github Repo branches.  have an exit branch to add as much and figure out how to organize.  Explain changes from Dev to 
1. Web - simple dev to meet scope of project, then shift to Django.  Use template to make things easier.  Hello Web app
2. Storage - free tier for AWS - note accumulation.
ACTION - billing review.  stop the server from running.
3. Learning - reading code is the best thing you can do
4. Grid Search CV will take a long time and a lot of power.  Figure out how to connect notebook to cloud services.
5. 2008 onward.  Same trends, similar.  2012 to now is better (that's what Zillow does) for home prices.
6. [2018, 2019]  loans are creeping up in quantity and ease of attainment to pre-recession levels.  Want to see what the results look like.
7. Once you do your final model, reduce the feature space as much as possible to reduce the processing.
[Flag in progress report] + one-pager on data structure
8. [feedback on final report and presentation]  Practice the presentation a lot and be open to Karen's comment.  
ACTION: Do a dry run, 3 weeks out.  Tell our story line.  Submit the progress report, what do we think we'll talk about in our slides.  Don't do that in the last week of the project. Look for available dates the last 2-3 weeks.  People do practice runs of presentation before they have final ideas, to make sure they have enough lead time to flesh things out.

9. Okay to be interactive.  Presentation for team is 20 minutes.  Get all of your points across.  In presentation-report; have as much as you can on approach.

10.  Hardest part is waiting for your models to finish.

11.  Fit evaluate---do for loops with different options, print out everything in Yellowbrick.  better to have same notebooks for the different years you'll do.  Take the output metrics and put it in data frame to compare later.

12.  3 weeks out---options to refactor modifications, use that readme file to be explanatory as possible.

**Comment by Anne-Kl** [comment]
+ update from 8/23 for AWS: key issue is cost.  Focus on scaling samples on local machine, and limit use of EC2 where possible to save $.  Write code for execution on local machine and in EC2.

Can review options for psuedo-hadoop (see District Data Labs discussion of this).  My reaction to psuedo-hadoop: given the time required for implementation, I lean towards having this as a second priority and trying it if we have time.  But I'm open to further discussion.

**Comment by Skenderbeu1405** [comment]
I think we got this covered, per our discussions and follow-ups in store for Monday Sept 2. As for pseudo-hadoop, no need for that anymore since I established a thourough data_structure flow (from raw->interim->processed) utilizing SQL files in notebooks and a multi-faceted stratified random sampling methodology. (See data_structure and notebooks > SQL for more).
