### ISSUE TITLE
ML model to run for 2013, 2015, and 2017 years on HMDA datasets

### ISSUE THREAD

**Issue by Skenderbeu1405** [georgetown-analytics/Loan-Canoe#2]
Using the scripts we will discuss at our call 08/11/2019 @ 6:30pm EST.

Tamana: to run for 2013
Blake: to run for 2015
Anne: to run for 2017 

By 08/11/2019 end of day. Review results in github "deploy" branch by 08/12/2019 12pm EST.

**Comment by Anne-Kl** [comment]
As of 8/14 we each have run initial models for all three years (Go Us!!!:) ).  The team is tracking to post their notebooks for each of the years this week.

**Comment by Skenderbeu1405** [comment]
This issue is resolved.
