### ISSUE TITLE
Question: Decision Trees vs. SVMs

### ISSUE THREAD

**Issue by Skenderbeu1405** [georgetown-analytics/Loan-Canoe#20]
Q: I'm considering using decision trees, or maybe even support Vector Machines -- I'm thinking this allows for more features. Would you suggest random forest over SVMs? Other thoughts?

**Comment by Anne-Kl** [comment]
Will note this as resolved given the superior Phase 3 performance of RandomForestClassifier.  LinearSVC was one of our best models in Phase 2 therefore further implications could merit additional exploration of SVM, but for purposes of our immediate need, we've resolved this.
