### ISSUE TITLE
Import Issue to postgreSQL AWS server

### ISSUE THREAD

**Issue by Skenderbeu1405** [georgetown-analytics/Loan-Canoe#3]
We are experiencing issues in this. I spoke to Anne, and she is getting out further details via e-mail. The take-away for simple solutions are thus:

(1) Definitive decision on some sort of cloud computing service (i.e. Blake to check AWS) -- will cost a bit of $ but the pros are that it's much faster, more secure than our local machine CPU.
OR
(2) Resolve in Python script -- cons: effort, need to learn code above and beyond, might not work super effectively; pros: free, good learning for DBMS + python integration technicals.

Issue to be resolved by Tuesday COB and to resolution to begin to be implemented/deployed by Wednesday 12pm EST.

**Comment by Anne-Kl** [comment]
Based on the 8/13 Discussion I lean towards (2) - writing a script that copies CSV data to Postgres as VARCHAR fields, to deal with the fact that PostgreSQL isn't handling COPY FROM for '' values very well.  We would then have to see if it works to recast the fields following the initial import.  I'll have time to look at this on 8/15.

**Comment by Skenderbeu1405** [comment]
Ok, I just did some fruther exploratory work on this. My conclusion: avoid using COPY FROM, as casting is difficult/I'm not familiar with it. 

(1) Use libraries to write directly in postgres server via engines -- it works well with using to_sql functions, I have had no trouble with it. The key is to use the postgreSQL command CAST first **note: you have to do a nested cast to go from text to varchar then varchar to int**.
--For more please see any of my scripts, but particularly helpful is the "v3__" and "REDACTED" scripts.
-- additionally,  for python specific bindings, please see the forked cfpb repo, in one of their notebooks they explain how to import/cast the time series HMDA data.

I will close this issue for now, as I think we have all the parts we need for our resolution. We can open it back up when we get to the "scaling our data up to include all years stage for production" in the next few days
