### ISSUE TITLE
Lat/Long for distance to city --> geopie(?)

### ISSUE THREAD

**Issue by Skenderbeu1405** [georgetown-analytics/Loan-Canoe#6]
For transforming county/state ; for looking at distance from and to big city; and for integration in web app Django (which Karen and team agreed people would love!).

**Comment by Anne-Kl** [comment]
Current ideas based on my research this week.  I am leaning toward seeing what results I get from exploratory clustering (1), and comparing to the ACP (2).  We can try running models with both.

1) Per 8/13 Discussion: Exploratory clustering, use lat/long to do Manhattan distance from an MSA.  GeoPy.  GoogleMaps.
2) American Communities Project (15 county types reflecting economic, demographic, and religious characteristics).  Data set available via: https://www.americancommunities.org/methodology/
3) USDA-ERS County Typology Codes - timestamp of 2013/2015.  Codes for metropolitan areas + " six mutually exclusive categories of economic dependence and six overlapping categories of policy-relevant themes." https://www.ers.usda.gov/data-products/county-typology-codes/

**Comment by Anne-Kl** [comment]
Resolved in final wrangling approach
