### ISSUE TITLE
Feature Selection -- Important notes and guidelines to resolve

### ISSUE THREAD

**Issue by Skenderbeu1405** [georgetown-analytics/Loan-Canoe#7]
Karen: (1) is there a groupin you can do on counties/states, dummies. You want to keep relationship but limit it to categories.
(2) can you do PCA? or LDA?

(3) consolidate your components --> grid search; evaluate performance of model by searching on different components.

==> K.B. : do a little bit of each approach -- i.e. do yellowbrick, do scikitlearn related projects, do a bit on lit review (ie statistical significances tests); careful of overfitting, then funnel down and decide what to include in your final.

**Issue to Resolve: (1) - (3): note on (3) -- we need to look at regularization techniques, the literature review, and draw upont prior work from instructor's Classifications books/techniques.**

**Comment by Skenderbeu1405** [comment]
KB: sci-kit learn and related projects (google and draw influences from credible repos).

**Comment by Anne-Kl** [comment]
Resolved via frequency feature
