### ISSUE TITLE
Unifying Our Approach on Modeling -- Concerns brought up to Karen

### ISSUE THREAD

**Issue by Skenderbeu1405** [georgetown-analytics/Loan-Canoe#8]
(1) Counties -- consider bucketing with a much narrower set (group in some way, perhaps lat/long => but certainly move away from the 1200+ dummies one hot key encoding generates here).

(2) Importance to transforming the other features

(3) Importance on sensitivity -- (false negative, i.e. if we are a thinktank, we dont care about banks making money, our story "we are ThinkTank LoanCanoe" and we want to empower people to know where and how they can get loans with the best possible rates for them."

**Comment by Anne-Kl** [comment]
Resolved in Phase 2 and 3 models
